title: "OpCode Solutions"
author:
  name: "OpCode Solutions"
  email: "info@opcodesolutions.com"
description: "Optimize Your Processes"

site_meta:
  lang:
    en:
      title: "OpCode Solutions"
      description: "Optimize Your Processes"
      toggle_nav: "Toggle navigation"
      development: "Development"
      saas: "SaaS"
      client_login: "Client Login"
      other_lang: "fr"
      other_lang_desc: "Français"
      privacy_policy: "Privacy Policy"
      optimal_browsing:
        title: "Optimal Browsing Technologies"
        description: 'We use <i>Optimal Browsing Technologies</i> to enhance your user experience and improve our service. By clicking "Accept" you agree to the use of these technologies. If you do not wish to proceed, click "Decline."'
        accept: "Accept"
        decline: "Decline"
    fr:
      title: "Solutions OpCode"
      description: "Optimisez vos processus"
      toggle_nav: "Changer la navigation"
      development: "Développement"
      saas: "SaaS"
      client_login: "Espace Client"
      other_lang: "en"
      other_lang_desc: "English"
      privacy_policy: "Politique de confidentialité"
      optimal_browsing:
        title: "Technologies de navigation optimales"
        description: "Nous utilisons des <i>Technologies de navigation optimales</i> pour améliorer votre expérience utilisateur et améliorer notre service. En cliquant sur « Accepter », vous acceptez l'utilisation de ces technologies. Si vous ne souhaitez pas continuer, cliquez sur « Refuser »."
        accept: "Accepter"
        decline: "Refuser"

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  # social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
main_pages:
  development:
    en:
      - en/solutions/index.html
      - en/demo/index.html
      - en/pricing/index.html
      - en/hosting/index.html
    fr:
      - fr/solutions/index.html
      - fr/demo/index.html
      - fr/prix/index.html
      - fr/hebergement/index.html
  saas:
    en:
      - en/saas/file-transfer/secure-file-sharing-solution/index.md
    fr:
      - fr/saas/transfert-de-fichiers/solution-de-partage-de-fichiers-securise/index.md
  en:
    - tech/index.md
    - en/contact/index.html
  fr:
    - tech/index.md
    - fr/contact/index.html
  privacy_policy:
    en: en/privacy-policy/index.md
    fr: fr/politique-de-confidentialite/index.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

exclude:
  - README.md
  - build-and-copy.sh
  - minima.gemspec
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
